apiVersion: apps/v1
kind: Deployment
metadata:
  name: quizapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quizapp
  template:
    metadata:
      labels:
        app: quizapp
    spec:
      containers:
      - name: quizapp-container
        image: quizapp:latest   # Using the "latest" tag here
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quizapp-service
spec:
  selector:
    app: quizapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
